### PR TITLE
Inline if statement added

### PR DESCRIPTION
**Pull request by rvangeldrop**

### CODE REVIEW

**Comment by jvanbaarsen** [comment]
@rvangeldrop Is there a reason @michiels is assigned?

**Comment by rvangeldrop** [comment]
No, just testing the features in Github :)

Verzonden vanaf mijn Samsung Galaxy-smartphone.
-------- Oorspronkelijk bericht --------Van: Jeroen van Baarsen notifications@github.com Datum: 14-08-16  17:47  (GMT+01:00) Aan: firmhouse/leanstartupnl-website leanstartupnl-website@noreply.github.com Cc: rvangeldrop robbert@firmhouse.com, Mention mention@noreply.github.com Onderwerp: Re: [firmhouse/leanstartupnl-website] Inline if statement added (#1) 
@rvangeldrop Is there a reason @michiels is assigned?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/firmhouse/leanstartupnl-website","title":"firmhouse/leanstartupnl-website","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/firmhouse/leanstartupnl-website"}},"updates":{"snippets":[{"icon":"PERSON","message":"@jvanbaarsen in #1: @rvangeldrop Is there a reason @michiels is assigned?"}],"action":{"name":"View Pull Request","url":"https://github.com/firmhouse/leanstartupnl-website/pull/1#issuecomment-239680593"}}}

**Comment by michiels** [comment]
@rvangeldrop i'm okay with this :) Does Jekyll support CoffeeScript in some way? :D

**Comment by rvangeldrop** [comment]
@michiels this: https://rubygems.org/gems/jekyll-coffeescript/versions/1.0.1 ?

**Pull request merged**
